style_image_path: styled_images/cubist.jpg 
# naming: "cubist" 
model_path: model/vgg_16.ckpt  
train_image_path: train2014/

content_weight: 1.0  
style_weight: 180.0  
# tv_weight: 0.0   

image_size: 256
batch_size: 4
epoch_num: 1

# loss_model: "vgg_16"
content_layers:  
  - "vgg_16/conv3/conv3_3"
style_layers:  
  - "vgg_16/conv1/conv1_2"
  - "vgg_16/conv2/conv2_2"
  - "vgg_16/conv3/conv3_3"
  - "vgg_16/conv4/conv4_3"
# checkpoint_exclude_scopes: "vgg_16/fc"  

channel_num: 3
train_check_point: model/trained_model/cubist/
test_image_path: test/test.jpg
image_save_path: image/
check_point_path: log/
learning_rate: 1e-3
data_size: 82783